<?php

function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array()('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAl_ITEM,
    );
    $items['shift_cipher_success'] = array(
        'title' => 'success',
        'page callback' => 'sum_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $itmes;
}

function shift_cipher_form() {
    $form['shift_cipher_container'] = array(
        'title' => 'Shift Cipher encryption',
        '#type' => 'fieldset',
    );
    $form['shift_cipher_container']['shift value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter a value between 1 and 26'),
        'element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,

    )
}
